version: 2.1

executors:
  node-docker-executor:
    docker:
      - image: circleci/node:11-browsers
    working_directory: ~/project

jobs:
  # Job to install dependencies and build the project
  build:
    executor: node-docker-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install  # Ensure all dependencies are installed
      - run:
          name: Build Docker Image
          command: |
            docker build -t pm4ml-ui-components .  # Build the Docker image
      - run:
          name: Build project
          command: yarn build  # Ensure webpack and other build steps are run
      - persist_to_workspace:
          root: ~/project
          paths:
            - node_modules  # Persist node_modules to workspace
            - dist  # Persist the build artifacts (dist, etc.)

  # Job to run tests inside the Docker container
  test:
    executor: node-docker-executor
    steps:
      - attach_workspace:
          at: /workspace  # Attach the workspace to access node_modules and build artifacts
      - checkout
      - run:
          name: Run Tests Inside Docker
          command: |
            docker run --name test-container --rm pm4ml-ui-components
      - run:
          name: Copy Test Results to Workspace
          command: |
            docker cp test-container:/usr/local/code/test-results.json /workspace/test-results.json || echo "No test results found"
      - store_test_results:
          path: /workspace/test-results.json
      - store_artifacts:
          path: /workspace/test-results.json
          destination: test-results.json

  # Job to run OWASP Dependency-Check
  vulnerability-test:
    docker:
      - image: owasp/dependency-check:latest
    steps:
      - attach_workspace:
          at: /workspace  # Attach the workspace to access build artifacts
      - checkout
      - run:
          name: Run OWASP Dependency-Check with NVD API Key
          command: |
            /usr/share/dependency-check/bin/dependency-check.sh \
              --project "$CIRCLE_PROJECT_REPONAME" \
              --scan /workspace/ \
              --format "HTML" \
              --out ./dependency-check-report.html \
              --nvdApiKey $NVD_API_KEY
      - store_artifacts:
          path: ./dependency-check-report.html
          destination: dependency-check-report.html

  # Job to publish to npm
  npm-publish:
    executor: node-docker-executor
    steps:
      - attach_workspace:
          at: /workspace  # Attach the workspace to access build artifacts
      - checkout
      - run:
          name: Set Up npm Credentials
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" > ~/.npmrc
      - run:
          name: Publish to npm
          command: |
            npm publish  # Publish the build to npm

workflows:
  version: 2
  build-test-scan-publish:
    jobs:
      - build
      - test:
          requires:
            - build
      #- vulnerability-test:
      #    requires:
      #      - build
      - npm-publish:
          requires:
            - test
