version: 2.1

executors:
  node-docker-executor:
    docker:
      - image: circleci/node:11-browsers
    working_directory: ~/project

jobs:
  # Job to build Docker image and run tests
  build-and-test:
    executor: node-docker-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: docker build -t pm4ml-ui-components .
      - run:
          name: Run Tests Inside Docker
          command: docker run --name test-container pm4ml-ui-components
      - run:
          name: Copy Test Results to Workspace
          command: docker cp test-container:/usr/local/code/test-results.xml ./test-results.xml || echo "No test results found"
      - store_test_results:
          path: ./test-results.xml
      - store_artifacts:
          path: ./test-results.xml
          destination: test-results.xml

  # Job to run OWASP Dependency-Check
  vulnerability-test:
    docker:
      - image: owasp/dependency-check:latest
    steps:
      - checkout
      - run:
          name: Run OWASP Dependency-Check with NVD API Key
          command: |
            /usr/share/dependency-check/bin/dependency-check.sh \
              --project "$CIRCLE_PROJECT_REPONAME" \
              --scan ./ \
              --format "HTML" \
              --out ./dependency-check-report.html \
              --nvdApiKey $NVD_API_KEY
      - store_artifacts:
          path: ./dependency-check-report.html
          destination: dependency-check-report.html

  # Job to publish to npm
  npm-publish:
    executor: node-docker-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install  # Ensure all dependencies are installed, including webpack
      - run:
          name: Set Up npm Credentials
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" > ~/.npmrc
      - run:
          name: Publish to npm
          command: |
            npm publish

workflows:
  version: 2
  build-test-scan-publish:
    jobs:
      - build-and-test
      - vulnerability-test:
          requires:
           - build-and-test
      - npm-publish:
          requires:
            - vulnerability-test