version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:11.15-browsers
    working_directory: ~/project

jobs:
  # Job to build the Docker image
  build-docker:
    executor: node-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: |
            docker build -t my-app .

  # Job to run the build using BuildSpec.yml
  build-spec:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: make install
      - run:
          name: Build Application
          command: make bare_build
      - run:
          name: Extract Artifacts
          command: make bare_extract
      - persist_to_workspace:
          root: ~/project
          paths:
            - "*.tgz"

  # Job to run the release build
  release-build:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: make install
      - run:
          name: Build for Release
          command: make bare_build
      - run:
          name: Extract Release Artifacts
          command: make bare_extract
      - persist_to_workspace:
          root: ~/project
          paths:
            - "*.tgz"

workflows:
  version: 2
  build-and-release:
    jobs:
      - build-docker
      - build-spec:
          requires:
            - build-docker
      - release-build:
          requires:
            - build-spec
