version: 2.1

executors:
  node-docker-executor:
    docker:
      - image: circleci/node:11-browsers
    working_directory: ~/project

jobs:
  build-and-test:
    executor: node-docker-executor
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.12
      - restore_cache:
          keys:
            - yarn-cache-{{ checksum "yarn.lock" }}
            - yarn-cache-
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Build Docker Image with Cache
          command: docker build --cache-from pm4ml-ui-components -t pm4ml-ui-components .
      - run:
          name: Run Tests Inside Docker
          command: docker run --name test-container pm4ml-ui-components
      - run:
          name: Copy Test Results to Workspace
          command: |
            if docker cp test-container:/usr/local/code/test-results.xml ./test-results.xml; then
              echo "Test results copied";
            else
              echo "No test results found, creating placeholder";
              touch ./test-results.xml;
            fi
      - store_test_results:
          path: ./test-results.xml
      - store_artifacts:
          path: ./test-results.xml
          destination: test-results.xml

  vulnerability-test:
    docker:
      - image: owasp/dependency-check:latest
    working_directory: ~/project
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-cache-{{ checksum "yarn.lock" }}
            - yarn-cache-
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: Validate NVD API Key
          command: |
            if [ -z "$NVD_API_KEY" ]; then
              echo "NVD_API_KEY is not set. Exiting.";
              exit 1;
            fi
      - run:
          name: Run OWASP Dependency-Check with NVD API Key
          command: |
            /usr/share/dependency-check/bin/dependency-check.sh \
              --project "$CIRCLE_PROJECT_REPONAME" \
              --scan ./ \
              --format "HTML" \
              --out ./dependency-check-report.html \
              --nvdApiKey $NVD_API_KEY \
              --disableYarnAudit || echo "Dependency-Check completed with warnings"
      - store_artifacts:
          path: ./dependency-check-report.html
          destination: dependency-check-report.html

  npm-publish:
    executor: node-docker-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-cache-{{ checksum "yarn.lock" }}
            - yarn-cache-
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Set Up npm Credentials
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" > ~/.npmrc
      - run:
          name: Publish to npm
          command: npm publish
      - run:
          name: Clean Up npm Credentials
          command: rm -f ~/.npmrc

workflows:
  version: 2
  build-test-scan-publish:
    jobs:
      - build-and-test
      - vulnerability-test:
          requires:
            - build-and-test
      - npm-publish:
          requires:
            - vulnerability-test